nome=input('Qual é o seu nome?')
dia=input('Qual dia você nasceu?')
mes=input('Qual mes do seu nascimento?')
ano=input('E em qual ano voce veio ao mundo?')
print('Olá',nome,'!','Seja ben vindo ao meu curso de programação python, você nasceu no dia',dia,'do mes de',mes,'no ano de',ano,' estou correto?')
