print('Olá, seja bem vindo ao calculador das 4 operações basicas de matematica(ADIÇÃO, SUBTRAÇÃO, DIVISÃO E MULTIPLICAÇÃO)')
print('informe abaixo dois algarismos para o programa funcionar')
n1=input('Primeiro numero')
n2=input('segundo numero')
soma=int(n1)+int(n2)
subtracao=int(n1)-int(n2)
divisao=int(n1)/int(n2)
multiplicacao=int(n1)*int(n2)
print('{}A soma dos dois numeros é {}}'.format(soma, bin(soma),soma,'.')
print('A subtração dos dois numeros é',subtracao,'.')
print('A divisão dos dois é',divisao,'.')
print('A multiplicação dos dois numeros é',multiplicacao,'.')